---
name: Security check - Bandit

on: push  # yamllint disable-line rule:truthy

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bandit security check for code
        uses: brunohaf/action-bandit@v1
        with:
          workdir: '.'
          bandit_config: './.bandit.code.yaml'

      - name: Bandit security check for tests
        uses: brunohaf/action-bandit@v1
        with:
          workdir: './src/darkgraylib/tests'
          bandit_config: './.bandit.tests.yaml'
