---
name: pylint

on: push  # yamllint disable-line rule:truthy

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies for running Pylint
        run: |
          pip install -U \
            defusedxml \
            pygments \
            "pylint<3.3.0" \
            "pytest>=6.2.0" \
            requests \
            requests-cache \
            ruamel.yaml \
            toml
          pip list
      - uses: wearerequired/lint-action@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pylint: true
          continue_on_error: false
