---
name: pyupgrade

on: push  # yamllint disable-line rule:truthy

jobs:
  pyupgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install pyupgrade
      - name: Ensure modern Python style using pyupgrade
        # This script is written in a Linux / macos / windows portable way
        run: |
          python -c "
          import sys
          from pyupgrade._main import main
          from glob import glob
          files = glob('**/*.py', recursive=True)
          sys.exit(main(files + ['--py39-plus']))
          " || ( git diff ; false )
